version: '3'

services:
  nextly-template:
    container_name: nextly-template-app
    build: .
    tty: true
    volumes:
      - type: bind
        source: .
        target: /app
    ports:
      - "3000:3000"
    environment:
      - NODE_OPTIONS=--openssl-legacy-provider
    command: yarn dev
