version: '3'

services:
  nextly-template:
    build: .
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - nextly_template_node_modules:/app/node_modules
    environment:
      - WATCHPACK_POLLING=true
    command: sh -c "cd /app && yarn dev"

# 以下追記
volumes:
  nextly_template_node_modules: